### ISSUE TITLE
Support multiple targets

### ISSUE THREAD

**Issue by jbeluch** [drone-plugins/drone-s3#44]
Hi, a feature I would love is to support multiple targets for the same set of source files without having to create 2 pipeline steps in your drone yaml. Thanks for the plugin!

**Comment by donny-dont** [comment]
@jbeluch please look at YAML anchors https://blog.daemonl.com/2016/02/yaml.html for a solution here.

**Comment by tboerger** [comment]
Beside the anchors, we keep most plugins simple, so it's absolutely common to add the plugin multiple times if you got different sets

**Comment by bradrydzewski** [comment]
I'm closing this because instead of supporting multiple targets we would recommend defining multiple steps. As mentioned one can use yaml anchors and jsonnet when 0.9 is released to reduce code duplication in the yaml when multiple steps are used. Alternatively, forking and maintaining a custom version of the plugin is always an option, and something we encourage when a plugin doesn't meet your exact needs.

**Comment by silverwind** [comment]
Could just accept an Array for `target`. Duplication of whole steps is not DRY and therefore error-prone 😉.
